version: '3.8'

services:
  api:
    build: .
    image: apivenezuelaearthquake-backend:latest
    container_name: apivenezuelaearthquake_api
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379
      - API_KEY=secure_apivenezuelaearthquake_key_v1_high_performance
      - CORS_ORIGINS=*
    env_file:
      - .env.dev # Por defecto carga variables en modo desarrollo si existe, de lo contrario .env
    depends_on:
      - redis_cache

  redis_cache:
    image: redis:7.0-alpine
    container_name: apivenezuelaearthquake_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
